version: "3.9"
services:

  db:
    image: postgres
    shm_size: 1g
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
    environment:
      POSTGRES_DB: "cloud"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "psw"
    ports:
      - "5432:5432"

  api:
    image: r0van/ya-disk-contest
    command: cloud-api fastapi
    ports:
      - "8081:8081"
    environment:
      CLOUD_PG_POOL_MAX_SIZE: 20
      CLOUD_PG_DSN: "postgresql://user:psw@db:5432/cloud"
      CLOUD_SLEEP: 0.01
