"""'Initial'

Revision ID: 303ac5f99463
Revises: 
Create Date: 2022-09-17 04:40:31.096580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303ac5f99463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('import_id', name=op.f('pk__imports'))
    )
    op.create_table('nodes',
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='type'), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.import_id'], name=op.f('fk__nodes__import_id__imports')),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.node_id'], name=op.f('fk__nodes__parent_id__nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', name=op.f('pk__nodes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    op.drop_table('imports')
    # ### end Alembic commands ###
