"""Initial

Revision ID: 975952a03049
Revises: 
Create Date: 2022-11-01 17:01:54.256361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975952a03049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__imports'))
    )
    op.create_table('folders',
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk__folders__import_id__imports')),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk__folders__parent_id__folders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__folders'))
    )
    op.create_table('files',
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk__files__import_id__imports')),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk__files__parent_id__folders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__files'))
    )
    op.create_table('folder_history',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk__folder_history__folder_id__folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk__folder_history__import_id__imports')),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk__folder_history__parent_id__folders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('import_id', 'folder_id', name=op.f('pk__folder_history'))
    )
    op.create_table('file_history',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk__file_history__file_id__files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk__file_history__import_id__imports')),
    sa.PrimaryKeyConstraint('import_id', 'file_id', name=op.f('pk__file_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_history')
    op.drop_table('folder_history')
    op.drop_table('files')
    op.drop_table('folders')
    op.drop_table('imports')
    # ### end Alembic commands ###
